
# notebook settings
[notebook]
dir = "~/notebook"
# SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Michael"


# GROUP OVERRIDES

[group.daily]
paths = ["flowstate"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.standup]
path = ["standup"]

[group.standup.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "standup.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# default shell
# shell = "/bin/bash"
# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "zk list --quiet --format full --limit 1 {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $argv"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# list notes for editing
ls = "zk edit --interactive"

# sear notes by tags
t = "zk edit --interactive --tag $argv"

config = 'nvim "$HOME/.config/zk/config.toml"'

# new journal entry
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/flowstate"'

ideas = 'zk new --no-input "$ZK_NOTEBOOK_DIR/ideas" --title $argv'

note = 'zk new --no-input "$ZK_NOTEBOOK_DIR/notes" --title $argv'

stdup = 'zk new --no-input "$ZK_NOTEBOOK_DIR/standup"'

# remove a files
rm = "zk list --interactive --quiet --format path --delimiter0 $argv | xargs -0 rm -vf --"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"


